[package]
name = "async_scoped_task"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
futures = "0.3.30"
tokio = { version = "1.36.0", features = ["rt-multi-thread", "macros"] }

[dependencies]
maybe-dangling = "0.1.1"
pin-project = "1.1.5"
slab = "0.4.9"
